sjrusso8/spark-connect-rs

Cargo.lock, Cargo.toml, README.md, examples/reader.rs, examples/sql.rs, examples/writer.rs, src/column.rs, src/dataframe.rs, src/expressions.rs, src/functions/mod.rs, src/lib.rs, src/plan.rs, src/readwriter.rs, src/session.rs, src/types.rs, src/utils.rs
* refactor some repeated code with marcos.
* add a lot new functions
* update documentation
=> feat: marco refactor and lots of functions

README.md, docker-compose.yml, examples/delta.rs, examples/writer.rs, src/column.rs, src/dataframe.rs, src/lib.rs, src/plan.rs, src/readwriter.rs, src/session.rs, src/storage.rs
feat(dataframe):
- implement more basic traits for DataFrame
- change interface to leverage Enums where possible (jointype, savemode, storagelevel)
- create storage.rs with enum wrapper around spark::StorageLevel
- create tests for _some_ of the traits
- update docker-compose.yml with delta-spark & add an example of reading a delta table
=> feat(dataframe): implement core traits

examples/delta.rs, examples/reader.rs, examples/writer.rs, src/catalog.rs, src/dataframe.rs, src/expressions.rs, src/functions/mod.rs, src/lib.rs, src/plan.rs, src/readwriter.rs
feat(generics): better generic args
- add better generic types to traits
- add new trait implementation for an array of expressions
- update example
Allow for statements like this in the `select` method.
```rust
df.select(["id", "value"])
// or like this
df.select([col("id"), col("value")])
// or like this too
df.select(vec![col("id"), col("value")])
```
All of which are translated to a vector expression.
Also there is better consistently for all function inputs. The default is `&str` for everything where a string input is needed. So all arguments that were `Vec<String>` are now `Vec<&str>`, etc.
=> feat: better generic args

Cargo.lock, Cargo.toml, README.md, examples/databricks.rs, examples/delta.rs, examples/reader.rs, examples/readstream.rs, examples/sql.rs, examples/writer.rs, src/catalog.rs, src/client/mod.rs, src/column.rs, src/dataframe.rs, src/errors.rs, src/expressions.rs, src/functions/mod.rs, src/group.rs, src/lib.rs, src/plan.rs, src/readwriter.rs, src/session.rs, src/storage.rs, src/streaming/mod.rs, src/types.rs
**Major Updates & Changes**
TL;DR 
- Streaming and GroupBy are implemented
- Most interfaces now return `Result`
- Added support for Timestamps and Dates 
- Drastically reduced the number of `clone` calls by actually handling ownership correctly
- Wrote unit tests
=> feat(updates): streaming & aggregations

README.md, examples/databricks.rs, examples/delta.rs, examples/reader.rs, examples/readstream.rs, examples/sql.rs, examples/writer.rs
- Update README with clearer "getting started" instructions
- Update the SQL example to match this gist https://gist.github.com/sjrusso8/2b4e43af462367a15f91db5a33627449
- Update other examples to explicitly set a remote URL 
- closes #14
=> chore: update readme & examples

README.md, src/column.rs, src/dataframe.rs, src/lib.rs, src/plan.rs, src/utils.rs, src/window.rs
feat(window): create Window & WindowSpec
- create two new structs for `Window` & `WindowSpec` based a similar implementation of the existing Spark API.
- add unit tests for coverage of specific Window methods
- add new `over` method onto `Column` and add unit test
- update Rust Docs and README for `Window
```rust
let df = spark.createDataFrame(&data)?;
let window = Window::new()
.partitionBy(col("category"))
.orderBy([col("id")])
.rowsBetween(Window::currentRow(), 1);
let df = df
.withColumn("sum", sum("id").over(window))
.sort([col("id"), col("category"), col("sum")]);
```
=> feat(window): create Window & WindowSpec

src/catalog.rs
feat(catalog): add additional methods
- add additional methods for `cacheTable`, 'databasesExists`, etc.
- did **not** include methods for `createTable`, `createExternalTable` or `registerFunction`
=> feat(catalog): add additional methods

src/catalog.rs, src/client/mod.rs, src/dataframe.rs, src/errors.rs, src/group.rs, src/lib.rs, src/plan.rs, src/readwriter.rs, src/session.rs, src/utils.rs, src/window.rs
feat: client improvements & flaky tests
- Update client mod to be more reusable
- Leverage environment variables for `SPARK_REMOTE` and `USER` 
- Move `SparkSessionBuilder` to `session` module
- Change `mutex` to `rwlock` when creating the client object
- Fix flaky tests
- Remove `arrow` as a re-export
=> feat: client improvements & flaky tests

core/src/dataframe.rs, core/src/group.rs, core/src/plan.rs, core/src/readwriter.rs, core/src/session.rs, core/src/streaming/mod.rs, core/src/window.rs
refactor: wrap all spark sessions in Box<>
- all spark sessions are now wrapped in a box
- cloning a box is fast and only clones the pointer and not the object
- update DataFrame create logic
- clean up code in the stream module
=> refactor: wrap all spark sessions in Box<>

core/src/dataframe.rs, core/src/readwriter.rs
Initial impl of DataframeWriterV2
Based off 
https://github.com/apache/spark/blob/master/connector/connect/client/jvm/src/main/scala/org/apache/spark/sql/DataFrameWriterV2.scala
and
https://github.com/apache/spark/blob/57b207774382e3a35345518ede5cfc028885f90b/sql/core/src/test/scala/org/apache/spark/sql/DataFrameWriterV2Suite.scala
=> feat: initial implementation of DataframeWriterV2

README.md, core/src/dataframe.rs
feat(dataframe): implement transform
- add method for `transform` that accepts a closure where the first param is a dataframe
This uses closures and differs slightly from the pyspark implementation. Pyspark allows for positional or kwargs args. It's a little tricky to implement that specific option in rust. So I opted for just a closure that accepts and returns a `DataFrame` and it's on the user to provide any additional args as part of the captured scope of the closure. 
```rust
let df = spark.range(None, 1, 1, None);
// closure with a captured value from the immediate scope
// results in the `lit` val being 100
let val: i64 = 100;
let func = |df: DataFrame| -> DataFrame { df.withColumn("new_col", lit(val)).select("new_col") };
// a dataframe with a column `new_col` and a value of `100` …
```
=> feat(dataframe): implement transform

core/src/client/mod.rs, core/src/session.rs
bug(tls): incorrect scheme for default endpoint
- needs to be `https` for only when using the `tls` feature
- closes #38
=> bug(tls): incorrect scheme for default endpoint

README.md, core/src/column.rs, core/src/dataframe.rs, core/src/expressions.rs, core/src/functions/mod.rs, core/src/readwriter.rs, core/src/types.rs, examples/src/reader.rs
Implement data types based on the Spark Data Types
- Create additional trait for `CastToDataType` to allow for a user to leverage `DataType` or `&str` when using `col("name").cast(...)`
- Added the `schema` method on the `DataFrameReader` to specify the read schema
- Create additional trait for `ToSchema` to allow users to specific a read schema using a `StructType` schema or `&str` representing a DDL string.
- Updated the `reader` example to show a type cast with a `DataType`
- Removed `ToProtoType` and implemented `From<T> for spark::DataType` instead. It's more idiomatic
- Misc: reorganized the code in the column module and changed up some variable names
- The `fromJson` method that `StructType` and `StructField` have on the current API. 
- The dataframe method for `schema()` still …
=> feat(data types): implement data types

README.md, core/src/client/mod.rs, core/src/column.rs, core/src/conf.rs, core/src/lib.rs, core/src/session.rs
feat(session): add RunTimeConfig & Session tags
- add the ability to get/set spark configs via `conf` and `appName`
- add the ability to get/set spark session tags
- fix issue with rust docs on the column
=> feat(session): add RunTimeConfig & Session tags

core/src/client/mod.rs, core/src/dataframe.rs, core/src/session.rs, examples/src/deltalake.rs, examples/src/sql.rs, examples/src/writer.rs
refactor(session): use ref for session methods & error messages
- change session methods to use `&self` where possible
- update `client` to remove `.unwrap()` and use `ok_or_else` instead
=> refactor(session): use ref for session methods & error messages

core/src/catalog.rs, core/src/column.rs, core/src/conf.rs, core/src/dataframe.rs, core/src/functions/mod.rs, core/src/group.rs, core/src/lib.rs, core/src/plan.rs, core/src/readwriter.rs, core/src/session.rs, core/src/streaming/mod.rs, core/src/window.rs, examples/src/databricks.rs, examples/src/deltalake.rs, examples/src/readstream.rs
refactor: remove snake case
- remove `allow(non_snake_case)` from everything
- update tests & other misc test fixes
- closes #36
=> refactor: remove non snake case

README.md, core/src/streaming/mod.rs, examples/src/readstream.rs
feat(sq): implement missing methods
- change `StreamingQuery` methods to `&self`
- add missing methods
=> feat(sq): implement missing methods

README.md, core/src/dataframe.rs, core/src/plan.rs, core/src/window.rs
feat(dataframe): implement missing methods
- implement missing methods for dataframe
All methods that are possible, except `observe` have been implemented. I don't like the implementation for `fill` or `na_replace` but they are okay for.
- closes #59
- closes #58 
- closes  #56
=> feat(dataframe): implement missing methods

core/src/functions/mod.rs
This pull request introduces additional test cases for the column functions. 
The new tests specifically evaluate the behavior of the following column functions:
- `asc_nulls_first`
- `asc_nulls_last`
- `desc_nulls_first`
- `desc_nulls_last`
- `like`
- `ilike`
- `rlike`
- `eq`
- `or`
- `isnotnull`
- `isnan`
- `alias`
- `cast`
- `substr`
, ensuring that they correctly identify and handle these cases.
Additionally, the `isnotnull` function definition has been moved to the appropriate section within the code, under `generate_functions!` for functions that require a single column argument, as well as a **typo** on the `subtract` function. This has been updated from `substract` to `subtract`.
-   Moved `isnotnull` function definition to:
```rust
// functions that require a single col argument …
```
=> Enhance Column Function Coverage with Additional Test Cases

.github/workflows/release.yml, core/src/functions/mod.rs
This PR adds the `working-directory` directive to the release workflow, ensuring the correct path is used for operations like comparing the Git tag with the Cargo metadata. As a result, the CI/CD release pipeline now runs successfully and triggers as expected when a tag is pushed.
- closes #64 
-   No additional documentation changes required
=> Resolve issue with broken CI/CD Release Pipeline

README.md, core/src/readwriter.rs
This pull request enables DataFrames to be **read from and written to various file formats** (CSV, JSON, ORC, Parquet) using a **set of predefined options** implemented via the `ConfigOpts` trait. Key changes include:
-   **DataFrameWriter:**
-   Implemented functionality to write DataFrames to `csv`, `json`, `orc`, `parquet` and `text` formats.
-   Added support for configuration options for various file formats (i.e `csv`, `json`, `orc`, `parquet` and `text`).
-   `ConfigOpts` trait implemented for `JsonOptions`, `OrcOptions`, and `ParquetOptions`.
-   Unit tests added to validate configuration options, similar to `TableOptions` tests in DataFusion.
-   **DataFrameReader:**
-   Enabled reading DataFrames from `csv`, `json`, `orc`, `parquet` and `text` formats.
-   Supported predefined …
=> Implement File Format Reader/Writer

core/src/column.rs, core/src/expressions.rs, core/src/functions/mod.rs
feat(functions): implement more functions
- implement nearly all of the remaining functions
- create a macro to quickly create simple functions
- create a macro to quickly create simple unit tests
- fix some doc references
Remaining functions are mostly the json and csv functions.
- closes #60 will open a new one with the remaining functions
=> feat(functions): implement more functions

core/src/dataframe.rs, core/src/errors.rs
feat(errors): cleaner handling of tonic status errors
-  update the error handling of Tonic status codes
-  change the error on the DataFrame for when the sessions are not the same
=> feat(errors): cleaner handling of tonic status errors

README.md, core/src/session.rs, core/src/streaming/mod.rs
feat(sqm): add streaming query manager
- add `StreamingQueryManager`
- methods for `await_any_termination`, `reset_termination`, `get`, and `active`
[PySpark StreamingQueryManager](https://spark.apache.org/docs/latest/api/python/reference/pyspark.ss/api/pyspark.sql.streaming.StreamingQueryManager.html?highlight=streamingquerymanager#pyspark.sql.streaming.StreamingQueryManager)
=> feat(sqm): add streaming query manager

crates/connect/src/catalog.rs, crates/connect/src/readwriter.rs
- Added create_table method to `catalog` for creating managed tables.
- Added create_external_table method to `catalog` for creating external tables.
- Implemented tests for managed and external table creation with schema validation.
This PR implements methods for creating both managed and external tables in the `catalog`.
- closes #55
=> feat(catalog): Implement createTable on Catalog

crates/connect/src/client/builder.rs, crates/connect/src/client/config.rs, crates/connect/src/client/mod.rs, crates/connect/src/session.rs
feat(config): add ability to control builder configurations
- provider finer grain control over the options used by the ChannelBuilder
- this is so users don't have to hack together a super long connection string to get custom headers into their session
=> feat(config): add ability to control builder configurations
