sjrusso8/spark-connect-rs

README.md
src/catalog.rs
src/dataframe.rs
src/handler/mod.rs
src/lib.rs
src/plan.rs
src/session.rs

- implemented the starting point for `catalog`
- added some missing DataFrame traits

Add Catalog & more DataFrame traits

---

src/column.rs
src/functions/mod.rs

- fix issue with logical not operator setup
- add unit test for functionality

bug(column): incorrect logical not

---

README.md
src/dataframe.rs
src/group.rs
src/plan.rs

feat(pivot/unpivot): implement pivot & unpivot
- add tests & update docs

feat: implement pivot & unpivot

---

Cargo.toml
docker-compose.yml

- Bump dependency and add feature flag for `send_guard` on `parking_lot`
- Bump spark version on docker compose

bump: dependencies & docker

---

.github/workflows/release.yml
core/Cargo.toml
rust/Cargo.toml

Update release pipeline and bump crate versions

fix: publish & bump versions

---

Cargo.lock
core/Cargo.toml

fix: add include to cargo.toml

---

.github/workflows/build.yml
Cargo.lock
Cargo.toml
README.md
core/Cargo.toml
core/src/dataframe.rs
core/src/errors.rs

feat(dataframe): Spark DF to Polars, DataFusion, or JSON
- from a spark dataframe create a `polars` [DataFrame](https://docs.rs/polars/latest/polars/frame/struct.DataFrame.html)
- from a spark dataframe create a `datafusion` [DataFrame](https://docs.rs/datafusion/latest/datafusion/dataframe/struct.DataFrame.html)
- from a spark dataframe create a JSON string with [toJSON](https://spark.apache.org/docs/3.1.3/api/python/reference/api/pyspark.sql.DataFrame.toJSON.html)

feat(dataframe): Spark DF to Polars, DataFusion, or JSON

---

core/src/conf.rs
core/src/session.rs

- bug(conf): runtimeconfig not working on wasm feature
- configs are not passed to the WASM client

bug(conf): runtimeconfig on wasm feature

---

Cargo.toml
core/Cargo.toml
examples/Cargo.toml

bug(dep): fix tokio dependeny on wasm feature
- issue with tokio dependency on RwLock and WASM

bug(dep): fix tokio dependeny on wasm feature

---

.gitmodules
core/Cargo.toml
core/build.rs
core/protobuf/spark-3.5/buf.yaml
core/protobuf/spark-3.5/spark/connect/base.proto
core/protobuf/spark-3.5/spark/connect/catalog.proto
core/protobuf/spark-3.5/spark/connect/commands.proto
core/protobuf/spark-3.5/spark/connect/common.proto
core/protobuf/spark-3.5/spark/connect/expressions.proto
core/protobuf/spark-3.5/spark/connect/relations.proto
core/protobuf/spark-3.5/spark/connect/types.proto

feat!(submodule): remove git submodule
- copy the protobuf from spark3.5 release
- update cargo.toml
closes: #62

feat!(submodule): remove git submodule

---

.github/workflows/build.yml

The description of the main changes of your pull request
fix(cicd): issue with docker compose
- change to `docker compose`

fix(cicd): issue with docker compose

---

Cargo.lock
Cargo.toml
README.md
core/Cargo.toml
core/src/dataframe.rs
core/src/expressions.rs
docker-compose.yml

chore: update readme & bump dependency

chore: update readme & bump dependency

---

core/src/catalog.rs
core/src/column.rs
core/src/dataframe.rs
core/src/expressions.rs
core/src/functions/mod.rs
core/src/group.rs
core/src/plan.rs
core/src/readwriter.rs
core/src/window.rs
examples/src/databricks.rs
examples/src/writer.rs

refactor: consolidate traits
- rewrite `expressions.rs` to use std traits like `Into`
- update all other code to use the new traits

refactor: consolidate traits

---

Cargo.lock
Cargo.toml
core/Cargo.toml
core/src/readwriter.rs
examples/src/databricks.rs

revert(tonic): move tonic back to 0.11
- issue with tls on tonic 0.12
- fix clippy warnings

revert(tonic): move tonic back to 0.11

---

README.md
crates/connect/src/catalog.rs
crates/connect/src/client/middleware.rs
crates/connect/src/client/mod.rs
crates/connect/src/column.rs
crates/connect/src/conf.rs
crates/connect/src/functions/mod.rs
crates/connect/src/group.rs
crates/connect/src/lib.rs
crates/connect/src/readwriter.rs

docs: update rustdocs 
- add docs to nearly every public facing API
- update some API visibility
- fix some typos
- fix examples

docs: update rustdocs

---

Cargo.lock
crates/connect/Cargo.toml
examples/Cargo.toml

bump: change crate version to `0.0.1`

chore: bump crate version

---

Cargo.lock
Cargo.toml
crates/connect/Cargo.toml
crates/connect/build.rs
crates/connect/src/conf.rs
crates/connect/src/session.rs

feat!(wasm): remove feature flag
- the `wasm` feature flag was experimental and is not really supported
Refer to the branch [feat/wasm](https://github.com/sjrusso8/spark-connect-rs/tree/feat/wasm) for a working example

feat!(wasm): remove feature flag

---

Cargo.lock
Cargo.toml
crates/connect/Cargo.toml
crates/connect/src/session.rs
docker-compose.yml

bump(docker): update docker and fix test
- fix flaky test

bump(docker): update docker and fix test

---

crates/connect/src/client/mod.rs

bug(reattach): connection is lost and session id is empty
- reattach would attempt to unwrap an empty session_id and operation_id. results in a panic.
- move the logic for `session_id`, `operation_id`, and `response_id` onto the Spark Client and off of the `ResponseHandler`
- A new `operation_id` is created for every new `ExecutePlanRequest` 
- remove fields from `ResponseHandler`
- closes #86 
Tested manually with long running job.

bug(reattach): connection is lost and session id is empty

---

Cargo.lock
crates/connect/Cargo.toml
examples/Cargo.toml

The description of the main changes of your pull request

bump: release

---

Cargo.lock
Cargo.toml
crates/connect/Cargo.toml
crates/connect/src/catalog.rs
crates/connect/src/client/builder.rs
crates/connect/src/client/middleware.rs
crates/connect/src/dataframe.rs
crates/connect/src/errors.rs
crates/connect/src/plan.rs
crates/connect/src/readwriter.rs
crates/connect/src/streaming/mod.rs
crates/connect/src/window.rs

Cleaned up some code:
- simplified the read configs by leveraging a macro for repeated sections
- add `thiserror` to simplify error codes
- bump dependencies for things that don't break everything
- clean up some unneeded `unwrap()` code
- clean up some tests

code clean up & dep bump
